import ThalesEmit.Render
import ThalesEmit.Ast
import ThalesEmit.Validate
import ThalesEmit.Format
import ThalesEmit.RoundTrip

/-! Syntax → text. The artifact is the rendered commands printed by Lean's
pretty-printer, joined with the fixed header and the source echo comments. -/

namespace ThalesEmit

open Lean

/-- The artifact's fixed header: scaffolding, not code the printer owns.
`autoImplicit` is pinned off because artifacts run under lean's defaults,
where an unbound identifier would auto-bind instead of erroring. -/
def header (e : Emission) : String :=
  s!"-- generated by thales-emit from {e.file}\n" ++
  "import ThalesDsl\n\n" ++
  "open Js ThalesDsl\n\n" ++
  "set_option autoImplicit false"

def commentLines (text : String) : String :=
  String.intercalate "\n"
    ((text.splitOn "\n").map fun line =>
      if line.isEmpty then "--" else s!"-- {line}")

/-- `Unhygienic` still stamps its one macro scope on quotation-literal
identifiers, which the printer would flag with `✝`; the artifact is
plain text, so the scopes are erased before printing. -/
partial def unscope : Syntax → Syntax
  | .ident info rawVal val preresolved =>
    .ident info rawVal val.eraseMacroScopes preresolved
  | .node info kind args => .node info kind (args.map unscope)
  | s => s

/-- Formatted command text, without trailing whitespace: the printer
leaves a dangling space after `then` when the arm breaks to its own line,
and the artifact is plain text a person's editor would flag it in. -/
def prettyLines (fmt : Format) : String :=
  String.intercalate "\n"
    (((fmt.pretty 100).splitOn "\n").map (·.dropEndWhile (· == ' ') |>.toString))

/-- The declaration's AST, as text under its model name: the decoded
closure as a `Tarski.Program` def, or — when the decoder refused a
construct — one comment line in the decoder's own message shape, which is
the recorded construct #481 turns into the model line's reason. A
declaration with no AST prints nothing at all, so an emission from before
this field renders exactly as it did. -/
def astBlock (base : Ident) : Option DeclAst → CoreM (Option String)
  | none => pure none
  | some (.unsupported k) =>
    pure (some s!"-- {(astIdent base).getId}: unsupported: {k}")
  | some (.program p) => do
    match RenderM.run (astCommand (astIdent base) p) with
    | .error msg => throwError msg
    | .ok cmd =>
      pure (some (prettyLines (← PrettyPrinter.ppCommand ⟨unscope cmd.raw⟩)))

/-- The class a residual site's owner names, for a member's site; none for
a free function's, whose opaque stands on its own. -/
def residualOwnerClass (r : EmitResidual) : Option String :=
  match r.owner.splitOn "#" with
  | [_] => none
  | c :: _ => some c
  | [] => none

/-- The full artifact text. Pretty-printing runs in `CoreM` against an
environment that imports `ThalesDsl`, which carries every syntax the
quotations build. -/
def renderEmission (e : Emission) : CoreM String := do
  let mut blocks : Array String := #[header e]
  -- A member's site is typed over the receiver, so its opaque cannot be
  -- declared before the structure that names it: the class prints its own
  -- sites between the structure and the members that apply them.
  let memberSites := e.declarations.filterMap fun d => match d with
    | .residual r => match residualOwnerClass r with
      | some c => some (r.module, c, r)
      | none => none
    | _ => none
  -- A dependency's declarations are contiguous and introduced by their
  -- module comment; the entry's carry none.
  let mut fromModule : Option String := none
  for d in e.declarations do
    -- A member's site is printed by its class, not here.
    if let .residual r := d then
      if (residualOwnerClass r).isSome then continue
    let module := match d with
      | .fn f => f.module | .cls c => c.module | .const c => c.module
      | .residual r => r.module
    if module != fromModule then
      fromModule := module
      if let some m := module then
        blocks := blocks.push s!"-- module {m}"
    match d with
    | .fn f =>
      let cmd ← rendered (fnCommand f)
      -- The source echo introduces the AST, both being what was
      -- written; the model def, which says what it means, is the block
      -- after them. With no AST the echo introduces the def, as before.
      let ast ← astBlock (← rendered' (modelIdent f.module f.name)) f.ast
      if let some ast := ast then
        blocks := blocks.push (commentLines f.source ++ "\n" ++ ast)
        blocks := blocks.push (prettyLines (← ppCommand cmd))
      else
        blocks := blocks.push
          (commentLines f.source ++ "\n" ++ prettyLines (← ppCommand cmd))
      -- The correspondence command reads the def and the AST above it, so
      -- it is the block after both; a dependency's declaration gets none.
      if let some v ← validateBlock e f.name (fnPlan e f) then
        blocks := blocks.push v
    | .const c =>
      let cmd ← rendered (constCommand c)
      let ast ← astBlock (← rendered' (modelIdent c.module c.name)) c.ast
      if let some ast := ast then
        blocks := blocks.push (commentLines c.source ++ "\n" ++ ast)
        blocks := blocks.push (prettyLines (← ppCommand cmd))
      else
        blocks := blocks.push
          (commentLines c.source ++ "\n" ++ prettyLines (← ppCommand cmd))
      if let some v ← validateBlock e c.name (constPlan c) then
        blocks := blocks.push v
    | .cls c =>
      -- The source echo introduces the structure; the constructor and
      -- each getter follow as their own blocks.
      let st ← rendered (structCommand c)
      blocks := blocks.push
        (commentLines c.source ++ "\n" ++ prettyLines (← ppCommand st))
      -- The members share the class's closure, so its AST sits with the
      -- structure, ahead of the sites and the constructor.
      if let some ast ← astBlock (← rendered' (classIdent c.module c.name)) c.ast then
        blocks := blocks.push ast
      for (m, cls, r) in memberSites do
        if m == c.module && cls == c.name then
          blocks := blocks.push (prettyLines (← ppCommand (← rendered (residualCommand r))))
      blocks := blocks.push (prettyLines (← ppCommand (← rendered (ctorCommand c))))
      for g in c.getters do
        blocks := blocks.push
          (prettyLines (← ppCommand (← rendered (getterCommand c g))))
      for m in c.methods do
        blocks := blocks.push
          (prettyLines (← ppCommand (← rendered (methodCommand c m))))
    | .residual r =>
      blocks := blocks.push (prettyLines (← ppCommand (← rendered (residualCommand r))))
  for o in e.obligations do
    let cmd ← rendered (obligationCommand e o)
    let text := prettyLines (← ppCommand cmd)
    -- What is printed is what the prover parses: a spelling the spine
    -- reader cannot recover fails here, not as a silent verdict degrade.
    checkRoundTrip o text
    blocks := blocks.push (s!"-- @ensures\{{o.property}} {o.formula}\n" ++ text)
  return String.intercalate "\n\n" blocks.toList ++ "\n"
where
  rendered (x : RenderM (TSyntax `command)) : CoreM (TSyntax `command) := do
    match RenderM.run x with
    | .error msg => throwError msg
    | .ok cmd => pure cmd
  /-- One declaration's `#thales_validate` block, or nothing when the
  plan says the declaration carries no command at all. Classes get none
  here: a member's obligation is #482's. -/
  validateBlock (e : Emission) (name : String) (plan : RenderM ValidatePlan) :
      CoreM (Option String) := do
    match RenderM.run (do validateCommand e.file name (← plan)) with
    | .error msg => throwError msg
    | .ok none => pure none
    | .ok (some cmd) => pure (some (prettyLines (← ppCommand cmd)))
  rendered' (x : RenderM Ident) : CoreM Ident := do
    match RenderM.run x with
    | .error msg => throwError msg
    | .ok id => pure id
  ppCommand (cmd : TSyntax `command) : CoreM Format :=
    PrettyPrinter.ppCommand ⟨unscope cmd.raw⟩

end ThalesEmit
