import { describe, it, expect, afterAll, beforeAll, beforeEach } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { announcedRunDir, runMain } from "./helpers/cli.js";
import { expectValidEnvelope } from "./helpers/envelope-schema.js";
import { clearRunDirs, seedRefuteProject } from "./helpers/refute-project.js";

const repoRoot = process.cwd();

// README usage claims about where a run's artifacts land: the envelope
// names the run directory, a later invocation reads none of an earlier
// one's mirrors, and a glob reports across every matched file. The
// generated tests import
// "@lakatos/pabst/runtime" via the workspace link, so these must run inside
// the repo tree (a gitignored scratch dir under .lakatos/), unlike the
// os.tmpdir()-based suites above.
describe("cli refute run directories", () => {
  const workDir = path.join(repoRoot, ".lakatos", "clitest-runs");

  beforeAll(() => {
    seedRefuteProject(workDir);
    process.chdir(workDir);
  });
  afterAll(() => {
    process.chdir(repoRoot);
    fs.rmSync(workDir, { recursive: true, force: true });
  });
  // Each test starts from a clean set of run directories; the tests that
  // exercise stale mirrors create their own staleness within the body.
  beforeEach(() => clearRunDirs(workDir));

  it(
    "refute's generated tests land under the run directory the envelope names",
    { timeout: 120000 },
    async () => {
      const { code, stderr } = await runMain(["refute", "good.ts"]);
      expect(code).toBe(0);
      const runDir = announcedRunDir(stderr);
      expect(
        fs.existsSync(path.join(runDir, "pabst", "good.ts.pabst.test.ts")),
      ).toBe(true);
      // vitest's own results are this run's business, not a sibling's.
      expect(
        fs.existsSync(path.join(runDir, "pabst", "vitest-results.json")),
      ).toBe(true);
    },
  );

  // The vitest run must be scoped to the out-files generated by THIS
  // invocation, not to every run directory sitting beside it.
  it(
    "back-to-back invocations do not leak issues from earlier runs",
    { timeout: 120000 },
    async () => {
      expect((await runMain(["refute", "bad.ts"])).code).toBe(1);
      // No wipe in between: bad.ts's own run directory is still there.
      const { code, stdout } = await runMain(["refute", "good.ts"]);
      expect(code).toBe(0);
      const env = JSON.parse(stdout[0]!);
      expect(env).toMatchObject({
        generated: 1,
        passed: 1,
        failed: 0,
        annotations: [{ file: "good.ts", szs: "GaveUp" }],
      });
    },
  );

  it(
    "a run that generates nothing reports a zero envelope, never stale mirrors",
    { timeout: 120000 },
    async () => {
      expect((await runMain(["refute", "bad.ts"])).code).toBe(1);
      const { code, stdout } = await runMain(["refute", "plain.ts"]);
      expect(code).toBe(0);
      const env = JSON.parse(stdout[0]!);
      expectValidEnvelope(env);
      expect(env).toMatchObject({
        generated: 0,
        passed: 0,
        failed: 0,
        annotations: [],
      });
    },
  );

  // End-to-end unhealthy run, no mocks: the module throws at load, so the
  // generated test can't even import it — vitest reports a file-level
  // failure with zero counted tests.
  it(
    "refute on a module that explodes at load prints a NotTried envelope and exits 2",
    { timeout: 60000 },
    async () => {
      const explosive = path.join(workDir, "explosive.ts");
      fs.writeFileSync(
        explosive,
        `/** @ensures{pos} forall (n: nat) { boom(n) >= 0 } */\nexport function boom(n: number): number { return n; }\nthrow new Error("boom: module exploded");\n`,
        "utf8",
      );
      try {
        const { code, stdout, stderr } = await runMain([
          "refute",
          "explosive.ts",
        ]);
        expect(code).toBe(2);
        expect(stdout).toHaveLength(1);
        const env = JSON.parse(stdout[0]!);
        expectValidEnvelope(env);
        expect(env).toMatchObject({ generated: 1 });
        expect(env.annotations).toEqual([
          {
            file: "explosive.ts",
            function: "boom",
            property: "pos",
            szs: "NotTried",
          },
        ]);
        expect(stderr.join("\n")).toContain("boom: module exploded");
      } finally {
        fs.rmSync(explosive, { force: true });
      }
    },
  );

  it(
    "refute accepts globs and reports across all matched files",
    { timeout: 60000 },
    async () => {
      const { code, stdout } = await runMain(["refute", "*.ts"]);
      expect(code).toBe(1);
      const env = JSON.parse(stdout[0]!);
      expectValidEnvelope(env);
      expect(env).toMatchObject({ generated: 2, passed: 1, failed: 1 });
      const flagged = env.annotations.filter(
        (a: { kind?: string }) => a.kind !== undefined,
      );
      expect(flagged).toHaveLength(1);
    },
  );
});
