import * as path from "node:path";
import { admit, refusalsOf } from "@lakatos/lemma";
import {
  UNSUPPORTED_RANGE_KIND,
  type PlannedProperty,
} from "@lakatos/core/envelope";
import { RUN_ROOT, TYPECHECK_CACHE } from "@lakatos/core/run-dir";
import {
  packageVersion,
  runTool,
  type RunReport,
  type Spine,
  type ToolIo,
} from "@lakatos/core/runner";
import { generate } from "./codegen.js";
import { joinRefuteVerdicts } from "./join.js";
import { runTests } from "./run.js";
import { randomSeed } from "./seed.js";

export interface RefuteOptions {
  /** fast-check's seed; a fresh random one when absent. The envelope echoes it. */
  seed?: number;
  /** Where notes and the envelope go; stderr and stdout when absent. */
  io?: ToolIo;
}

/**
 * Refute every `@ensures` annotation in the files `patterns` name, or in
 * the files tsconfig.json compiles when there are none, from the current
 * directory. Resolves to the envelope and the exit code the bin reports;
 * rejects with LemmaError on bad input and RunDirError on an unusable run
 * root.
 */
export function refute(
  patterns: string[],
  options: RefuteOptions = {},
): Promise<RunReport> {
  return runTool(
    { name: "pabst", version: packageVersion(import.meta.url) },
    () => admit(patterns, path.resolve(RUN_ROOT, TYPECHECK_CACHE)),
    refuteSpine(options.seed ?? randomSeed()),
    options.io,
  );
}

function refuteSpine(seed: number): Spine {
  return {
    plan(files, runDir, refused) {
      const outRoot = path.join(runDir, "pabst");
      const results = generate(files, outRoot, seed, refused);
      const identities: PlannedProperty[] = results.flatMap((r) =>
        r.properties.map((p) => ({ file: r.sourceFile, ...p })),
      );
      const inputErrors = results.flatMap((r) =>
        refusalsOf(r.sourceFile, r.invalid),
      );
      const generated = identities.length;
      const notes = [
        {
          level: "info" as const,
          text: `generated ${generated} propert${generated === 1 ? "y" : "ies"} across ${results.length} file(s) into ${outRoot}/`,
        },
      ];
      // Scope the run to the out-files generated by THIS invocation, not the
      // whole directory: an empty file list would tell vitest to run
      // everything, so the runner short-circuits when nothing was generated.
      return {
        identities,
        untried: results.flatMap((r) =>
          r.untried.map((u) => ({
            file: r.sourceFile,
            function: u.function,
            property: u.property,
            szs: "NotTried" as const,
            kind: UNSUPPORTED_RANGE_KIND,
            reason: u.reason,
          })),
        ),
        inputErrors,
        notes,
        degraded: false,
        outFiles: results.flatMap((r) =>
          r.outFile !== undefined ? [r.outFile] : [],
        ),
        meta: { seed, generated },
        emptyMeta: { passed: 0, failed: 0 },
        emptyExit: 0,
      };
    },

    run(plan, runDir) {
      const result = runTests(
        plan.outFiles,
        path.join(runDir, "pabst", "vitest-results.json"),
      );
      if (result.kind === "interrupted")
        return { kind: "interrupted", signal: result.signal };
      // Unhealthy runs (vitest died before reporting, or the generated suite
      // failed to load) still honor the output contract: diagnostics on
      // stderr, a NotTried envelope on stdout, and the documented exit 2,
      // not vitest's raw status.
      if (result.kind !== "completed") {
        if (result.kind === "no-results") {
          process.stderr.write(result.stdout);
          process.stderr.write(result.stderr);
          return { kind: "unhealthy", messages: [] };
        }
        return { kind: "unhealthy", messages: result.messages };
      }
      const join = joinRefuteVerdicts(plan.identities, result.json);
      // A failure the join cannot read means the reporter never ran; that is
      // engine breakage, contained like a run that reported nothing at all.
      if (join.kind === "unreadable")
        return { kind: "unhealthy", messages: join.messages };
      const failed = result.json.numFailedTests;
      return {
        kind: "completed",
        annotations: join.annotations,
        meta: { passed: result.json.numPassedTests, failed },
        degraded: false,
        // A failing test is a refutation whatever kind of issue it carried:
        // the count, not the SZS status, is what the exit code reports.
        refuted: failed > 0,
      };
    },
  };
}
